# Generated by Django 4.0.6 on 2022-07-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='name',
            new_name='branch_name',
        ),
    ]
